### ISSUE TITLE
Feature | Add tests for MFA and SSO scripts

### ISSUE THREAD

**Issue by juanmatias** [binbashar/le-docker-leverage-toolbox#22]
## Describe the Enhancement

The MFA and SSO scripts should be tested when testing the toolbox.

## Expected Behavior

These script set being tested before releasing.

## Use Case

There are a few scripts included in the image to handle MFA and SSO.
These scripts should be tested before they are sent into the wild.

## Describe Ideal Solution

Test have to be created, what can be tested of these scripts? Cover as much as possible.

## Alternatives Considered

n/a

## Additional Context
n/a

**Comment by exequielrafaela** [comment]
Solved in https://github.com/binbashar/leverage/pull/232
