### ISSUE TITLE
Enhancement | Update AWS CLI in the docker toolbox image

### ISSUE THREAD

**Issue by juanmatias** [binbashar/le-docker-leverage-toolbox#30]
## Describe the Enhancement

As per this PR: https://github.com/binbashar/leverage/issues/148

>Use version ~= 2.7.32
>
>EDIT: I think the problem we were having was with using the AWS CLI to generage the Kubernetes config file. I believe such file was generated with an old apiVersion, e.g. apiVersion: client.authentication.k8s.io/v1beta1. Updating the AWS CLI version should fix that.

**Comment by exequielrafaela** [comment]
@rodriguez-matias @juanmatias I'll proceed to close this issue, remember we must update the doc too 🙏🏼 https://github.com/binbashar/le-ref-architecture-doc/issues/144
