### ISSUE TITLE
Enhancement | automatically enter code when aws sso login

### ISSUE THREAD

**Issue by juanmatias** [binbashar/le-docker-leverage-toolbox#36]
## Describe the Enhancement

When using AWS CLI doing:

```shell
aws sso login
```

A webpage is automatically opened, and the generated code is sent to it by the AWS CLI. (i.e. no need to enter it manually)

When doing the same from leverage:

```shell
leverage aws sso login
```

The same webpage is opened but the code is not sent automatically.

## Expected Behavior

The behavior should be the same, whenever possible, in both cases.

## Use Case

A user trying to use the SSO Login feature.

## Describe Ideal Solution

The ideal solution is when opening the webpage the code is entered automatically.

## Alternatives Considered

Since Leverage CLI is not trapping the `open` command from the AWS CLI, it can remain as a manual input.

## Additional Context

Take into account the `--no-browser` for AWS CLI.

**Comment by exequielrafaela** [comment]
@juanmatias thanks for creating this issue, it sounds like a great UX improvement! 

CC: @angelofenoglio @diego-ojeda-binbash
