### ISSUE TITLE
Bug | Bad sso logout process

### ISSUE THREAD

**Issue by juanmatias** [binbashar/le-docker-leverage-toolbox#48]
## Describe the Bug

When using SSO, running the `leverage aws sso logout` command leads to an inconsistent scenario in which the credentials are unusable.

When running a Terraform command in a layer the profile used by Terraform is created with credentials got from SSO profiles.
In this process the credentials are stored in `credentials` file, and the expiration time is stored in `config` file.

When logging out the credentials file is deleted, also the sso profiles in config file are deleted, but the profile used by Terraform is left in config file. 
 
When running a new Terraform command, Leverage finds the profile in the config file with a valid expiration date, but there are no credentials in credentials file, thus it fails. 

## Expected Behavior

The profile should be deleted in both credentials and config file so it can be created later when a new Terraform command is run.

## Steps to Reproduce

1. `leverage aws configure sso`
2. `leverage tf init`
3. `leverage aws sso logout`
4. `leverage aws configure sso`
5. `leverage tf init`

```shell
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│ 
│ 
│ 
╵

```

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - Leverage CLI 1.10.0
 - Leverage Toolbox 1.2.7-0.1.8

## Additional Context

https://github.com/binbashar/le-docker-leverage-toolbox/blob/83dcaececa06f6f3da85bc7af8fde78b83ff47c2/scripts/aws-sso/aws-sso-logout.sh#L45-L57

**Comment by exequielrafaela** [comment]
- `leverage aws sso logout` should only clean the `.aws/short_project/cache/token`, and not removing or modifying the `.aws/short_project/config`
- Update doc https://leverage.binbash.com.ar/user-guide/leverage-cli/reference/aws/#usage with an admonition (rec, tip or info) in order to explain that if your're working with IAM and migrating to SSO you'll need to backup your aws creds before since they're going to regenrated @diego-ojeda-binbash
