### ISSUE TITLE
Enhancement | support for more platforms

### ISSUE THREAD

**Issue by juanmatias** [binbashar/le-docker-leverage-toolbox#50]
## Describe the Enhancement

As per this issue https://github.com/binbashar/le-docker-leverage-toolbox/issues/46 and this PR https://github.com/binbashar/le-docker-leverage-toolbox/pull/49 logic was added for downloading platform-specific tools.
Also, support for `linux/amd64` and `linux/arm64` was added.

Since `buildx` is being used for building the multi platform images, and given this tool supports other platforms, this enhancement is aimed to add support for more platforms in the case:
* it make sense to add such a platform (e.g. there are users owning these platforms)
* there are specific tools for such platforms
 
## Expected Behavior

Support as many platforms as possible whether it makes sense. (e.g. users needing this support)

## Use Case

Users owning a platform other than `amd64` and `arm64`.

## Describe Ideal Solution

Support all the users needs.

## Alternatives Considered

Keep going just with `amd64` and `arm64`.

## Additional Context

As per [this page](https://docs.docker.com/build/building/multi-platform/) in Docker site:
> Most of the Docker Official Images on Docker Hub provide a [variety of architectures](https://github.com/docker-library/official-images#architectures-other-than-amd64). For example, the busybox image supports amd64, arm32v5, arm32v6, arm32v7, arm64v8, i386, ppc64le, and s390x. When running this image on an x86_64 / amd64 machine, the amd64 variant is pulled and run.

**Comment by exequielrafaela** [comment]
Even if this could be seen as nice to have, for the moment the current supported architectures cover our main use cases (https://github.com/binbashar/le-dev-makefiles/blob/28182694f82d2a3e1bd624d2cd3fcbd1df56a660/docker/docker-hub-build-push-single-arg-multi-arch.mk#L20C30-L20C53). 

We'll close this issue till customer projects or the community require it. This will give more space to work on more urgent fixes and features.
